### ISSUE TITLE
VS 2022 not installed when in Windows Sandbox

### ISSUE THREAD

**Issue by jptemplin** [wrljet/hercules-helper-windows#3]
I'm trying to build Hercules in a Windows Sandbox to isolate the build environment from my main PC.

I invoked the script as follows:
PS C:\Users\WDAGUtilityAccount> cd .\Documents
PS C:\Users\WDAGUtilityAccount\Documents> .\hercules-buildall.ps1 -VS2022 -BuildDir c:\hercules 

The script fails here:
==> VS2022 will require updating.  Ctrl+C now if you don't want that.
==> Run VS2022 installer to update (this will take some time)
'.\vs_community.exe' is not recognized as an internal or 
external command,
operable program or batch file.

And that .exe is indeed in the directory. Screen shot and log attached.

[hercules-helper-20230616_13-35-54.log](https://github.com/wrljet/hercules-helper-windows/files/11772799/hercules-helper-20230616_13-35-54.log)
![Directory Capture](https://github.com/wrljet/hercules-helper-windows/assets/51379861/241a5baf-6ab4-4813-af57-db2d9339f023)

**Comment by wrljet** [comment]
I had never heard of Windows Sandbox before this.

I dusted off a Windows 10 Enterprise VMware machine.  Got Windows Sandbox install/working in there.
And I have reproduced your symptoms easily.

The problem is actually occurring a bit earlier then where it is reported.
In `.\create-vs2022-offline.ps1`, while running `vs_community.exe`, the bootstrapper is supposed to be downloading quite a lot of files (2.8 GB) into the `vs2022offline` directory.  But that fails and gives up almost immediately without any error message that I can see.

I tried a newer/current PowerShell.  And aslo ran that As Admin.  With no effect.

You can run  `.\create-vs2022-offline.ps1` by itself and see the download window opens up.  It mentions one download and then closes.  Normally there would be dozens of files downloaded there.

The failed bootstrapper process did, however, leave me with a working Visual Studio Installer, off the Start menu.
This can be used as a GUI program to import the config I've attached here (zipped, to get it past GitHub), which will then install all the required workloads.

[hercules2022.vsconfig.zip](https://github.com/wrljet/hercules-helper-windows/files/11774310/hercules2022.vsconfig.zip)

After doing that, rerunning ` .\hercules-buildall.ps1 -VS2022 -BuildDir c:\hercules` it should find the required VS2022 workloads all present, and then it continue and builds Hercules.  (at least it did for me)

Bill

**Comment by jptemplin** [comment]
Hi Bill,

Thanks for the replay and the .zip file.

What I ended up doing was preinstalling the Visual Studio Installer and using your hercules2022.vsconfig.zip to import the config for all the workloads. Then I ran the script using the same command line as above. Everything built, but some of the tests failed. 

"3211 printer (OORexx)":  0 OK compares.  2 failures.
<snip>
Did 235 tests.  1 failed; 234 OK.

Log attached.

[hercules-helper-20230616_16-30-35.log](https://github.com/wrljet/hercules-helper-windows/files/11775784/hercules-helper-20230616_16-30-35.log)

**Comment by wrljet** [comment]
Yeah, I got that failed test, too.  I wouldn't worry about that. :)

**Comment by wrljet** [comment]
Is my understanding correct that if the Sandbox window is closed, it will throw out everything done there?

Not being sure, I paused my VMware when I was done with the experiment.

**Comment by jptemplin** [comment]
> Is my understanding correct that if the Sandbox window is closed, it will throw out everything done there?

Yes, that's correct. In this use case, I would build Hercules in a Windows Sandbox, copy off the relevant build products, then discard the sandbox. I don't need to keep that customized copy of Visual Studio hanging around.

**Comment by wrljet** [comment]
The 4.6 release artifacts include binaries for Windows.  (although not built with a modern VS)
So, may I ask, just being nosy, why you are building Hercules for Windows from source?

And, you can use the `-GitBranch` or `-GitCommit` options if you want to build something more specific.

**Comment by jptemplin** [comment]
> So, may I ask, just being nosy, why you are building Hercules for Windows from source?

Fish referenced your project in a recent Hercules-390 groups.io post. It piqued my curiosity; I was always curious how difficult it would be to build the Windows version from source since the Linux folks do it all the time. More technical curiosity than anything else.

You may close this issue. Thanks for your help.

**Comment by wrljet** [comment]
I see.

The process doesn't upset your Windows system too badly.  (other than the huge size of Visual Studio)
There's really only one directory squirreled away in no-mans-land my contraption writes to, related to the VS profiles.  And those files are tiny.  Other than that it's pretty easy to just erase everything.

FWIW, Linux folks have plenty of trouble building Hercules! :)

Thanks for trying it out!

Bill

**Comment by wrljet** [comment]
I figured I'd mention, as well...

Once things are primed (such as from Hercules-Helper), it's quite easy to build Hercules from the "Visual Studio Native Tools Command Prompt".

Adjust directories here to suit:

```
cd hyperion\

set ZLIB_DIR=c:\xfer\hercules\hyperion\winbuild\zlib
set BZIP2_DIR=c:\xfer\hercules\hyperion\winbuild\bzip2
set PCRE_DIR=c:\xfer\hercules\hyperion\winbuild\pcre

call makefile.bat RETAIL makefile.msvc 8 -title "*** Test Build ***" -a
```

Bill
